import type { Certification } from './schema';

/**
 * Certifications from the LinkedIn export, deduped and newest-first.
 * Grouped by `category` in the Credentials section; URLs verify each one.
 */
export const certifications: Certification[] = [
  {
    name: 'Voice for AI Agents and Applications',
    authority: 'DeepLearning.AI',
    date: 'Jul 2026',
    url: 'https://learn.deeplearning.ai/accomplishments/768fdc10-f1cf-4e9e-9753-f2ba88eb44bf',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Build Interactive Agents with Generative UI',
    authority: 'DeepLearning.AI',
    date: 'Jul 2026',
    url: 'https://learn.deeplearning.ai/accomplishments/0c1e30be-114f-4bf6-a663-4cfdb12eb01a',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'AI Agents for Image and Video Generation',
    authority: 'DeepLearning.AI',
    date: 'Jun 2026',
    url: 'https://learn.deeplearning.ai/accomplishments/fb649291-392d-4b62-842f-947029030e82',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Fast & Efficient LLM Inference with vLLM',
    authority: 'DeepLearning.AI',
    date: 'Jun 2026',
    url: 'https://learn.deeplearning.ai/accomplishments/eb529c4f-d620-40a0-bb40-06a3600e22ac',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Spec-Driven Development with Coding Agents',
    authority: 'DeepLearning.AI',
    date: 'Jun 2026',
    url: 'https://learn.deeplearning.ai/accomplishments/8375b131-bd8e-4269-8cd0-59f84e9bb794',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'LLM Engineering - Master AI, Large Language Models & Agents',
    authority: 'Udemy',
    date: 'Aug 2025',
    url: 'https://www.udemy.com/certificate/UC-fa593fOf-ee13-4cc1-b7aa-9a8519d486c9/',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Claude Code: A Highly Agentic Coding Assistant',
    authority: 'DeepLearning.AI',
    date: 'Aug 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/959d85dd-aa29-4571-8125-1b0b0657b7c3',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'MCP: Build Rich-Context AI Apps with Anthropic',
    authority: 'DeepLearning.AI',
    date: 'May 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/c3369639-1332-47ae-a670-de025e2f2615',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Building AI Browser Agents',
    authority: 'DeepLearning.AI',
    date: 'May 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/0d81369f-165b-4df2-ada4-86f07caf4f71',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Building Code Agents with Hugging Face smolagents',
    authority: 'DeepLearning.AI',
    date: 'May 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/dba5ec84-8b8e-4b00-aaad-d80b15726f99',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Vibe Coding 101 with Replit',
    authority: 'DeepLearning.AI',
    date: 'Apr 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/cb1884d0-ec83-4063-92b6-b2efe7e9d427',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Knowledge Graphs for RAG',
    authority: 'DeepLearning.AI',
    date: 'Mar 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/4557eaf3-4710-4247-9527-fda50d72437d',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Build Apps with Windsurf’s AI Coding Agents',
    authority: 'DeepLearning.AI',
    date: 'Mar 2025',
    url: 'https://learn.deeplearning.ai/accomplishments/199f739e-95da-4d11-b565-baf68ec9ce6f',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Team Software Engineering with AI',
    authority: 'Coursera',
    date: 'Feb 2025',
    url: 'https://www.coursera.org/account/accomplishments/verify/HD1B0R7LHFJJ',
    category: 'AI for Software Development',
  },
  {
    name: 'AI-Powered Software and System Design',
    authority: 'Coursera',
    date: 'Feb 2025',
    url: 'https://www.coursera.org/account/accomplishments/records/DORICO2VI2D3',
    category: 'AI for Software Development',
  },
  {
    name: 'Introduction to Generative AI for Software Development',
    authority: 'Coursera',
    date: 'Feb 2025',
    url: 'https://www.coursera.org/account/accomplishments/records/8QJ16YGBUIIZ',
    category: 'AI for Software Development',
  },
  {
    name: 'Generative AI for Software Development Specialization',
    authority: 'Coursera',
    date: 'Feb 2025',
    url: 'https://www.coursera.org/account/accomplishments/specialization/0APRQWO4KRMQ',
    category: 'AI for Software Development',
  },
  {
    name: 'Functions, Tools and Agents with LangChain',
    authority: 'DeepLearning.AI',
    date: 'Aug 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/4ba17a3c-832a-423b-af11-3c2dd83785fc',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Improving Accuracy of LLM Applications',
    authority: 'DeepLearning.AI',
    date: 'Aug 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/14d3c89b-525f-4f87-8f6b-ee6eda0561a3',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Function-calling and data extraction with LLMs',
    authority: 'DeepLearning.AI',
    date: 'Jul 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/1bea519b-5b75-459e-8817-1775dbe1734a',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Building Your Own Database Agent',
    authority: 'DeepLearning.AI',
    date: 'Jul 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/c94bf9ed-40de-4906-a675-14015ff77282',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Multi AI Agent Systems with crewAI',
    authority: 'DeepLearning.AI',
    date: 'Jun 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/448a5f84-91e2-4a5e-9e98-bddd8780bfe2',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'AI Agents in LangGraph',
    authority: 'DeepLearning.AI',
    date: 'Jun 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/d031aea4-f499-4838-a0a2-f61382767b27',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'AI Agentic Design Patterns with AutoGen',
    authority: 'DeepLearning.AI',
    date: 'Jun 2024',
    url: 'https://learn.deeplearning.ai/accomplishments/c0ceb2e8-843e-45b6-8a3f-481c462b5edc',
    category: 'AI Agents & LLM Engineering',
  },
  {
    name: 'Google Cloud Fundamentals for AWS Professionals',
    authority: 'Google Cloud Skills Boost',
    date: 'Apr 2023',
    url: 'https://www.cloudskillsboost.google/public_profiles/1c0010fb-4afe-486c-923f-18af0a17bb31/badges/3426499',
    category: 'Cloud (Google Cloud)',
  },
  {
    name: 'Perform Foundational Infrastructure Tasks in Google Cloud',
    authority: 'Google Cloud Skills Boost',
    date: 'Mar 2023',
    url: 'https://www.cloudskillsboost.google/public_profiles/1c0010fb-4afe-486c-923f-18af0a17bb31/badges/3293291',
    category: 'Cloud (Google Cloud)',
  },
  {
    name: 'Google Cloud Fundamentals: Core Infrastructure',
    authority: 'Google Cloud Skills Boost',
    date: 'Mar 2023',
    url: 'https://www.cloudskillsboost.google/public_profiles/1c0010fb-4afe-486c-923f-18af0a17bb31/badges/3256830',
    category: 'Cloud (Google Cloud)',
  },
  {
    name: 'Google Cloud Big Data and Machine Learning Fundamentals',
    authority: 'Google Cloud Skills Boost',
    date: 'Mar 2023',
    url: 'https://www.cloudskillsboost.google/public_profiles/1c0010fb-4afe-486c-923f-18af0a17bb31/badges/3353001',
    category: 'Cloud (Google Cloud)',
  },
  {
    name: 'Create and Manage Cloud Resources',
    authority: 'Google Cloud Skills Boost',
    date: 'Feb 2023',
    url: 'https://www.cloudskillsboost.google/public_profiles/1c0010fb-4afe-486c-923f-18af0a17bb31/badges/3220988',
    category: 'Cloud (Google Cloud)',
  },
  {
    name: 'Deep Learning Specialization',
    authority: 'Coursera',
    date: 'Jul 2021',
    url: 'https://www.coursera.org/account/accomplishments/specialization/certificate/P9ZDTBCVBTLX',
    category: 'ML & Data Science',
  },
  {
    name: 'Python SDET-Backend Rest API Testing with BDD Framework',
    authority: 'Udemy',
    date: 'Dec 2020',
    url: 'https://tm.udemy.com/certificate/UC-df2fc70b-3d07-458e-9b45-84d10655d7f3/',
    category: 'Testing & Foundations',
  },
  {
    name: 'Creativity, Design Thinking and Innovation for Business',
    authority: 'Udemy',
    date: 'Nov 2020',
    url: 'https://tm.udemy.com/certificate/UC-2c1426ca-8edd-40e5-a10b-d3e2b0136a30/',
    category: 'Testing & Foundations',
  },
  {
    name: 'Machine Learning',
    authority: 'Coursera',
    date: 'Mar 2020',
    url: 'https://www.coursera.org/account/accomplishments/certificate/3JYL4LB5LVU2',
    category: 'ML & Data Science',
  },
  {
    name: 'Python for Data Science and Machine Learning Bootcamp',
    authority: 'Udemy',
    date: 'Mar 2020',
    url: 'https://tm.udemy.com/certificate/UC-a906ce78-0c7b-4306-aa3f-5c50fc9c2c79/',
    category: 'ML & Data Science',
  },
];
